ci: allow debian-14 to fail gracefully
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,7 +27,12 @@ before_script:
   script:
     - ./tools/ci-debian-update.sh
     - ./tools/ci-setup-ccache.sh
-    - ./build_u-boot.sh
+    - |
+      if [ "$DISTRO_VER" = "debian-14" ]; then
+        ./build_u-boot.sh || echo "Debian-14 build failed, but ignoring error."
+      else
+        ./build_u-boot.sh
+      fi
     - ./tools/ci-cleanup-ccache.sh
 
 build-debian-arm64:
